spring:
  config:
    activate:
      on-profile: postgres-int
  datasource:
    driver-class-name: org.postgresql.Driver
    # URL, Username, Password werden dynamisch durch @DynamicPropertySource aus dem Test gesetzt
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  flyway:
    enabled: true
    # Nur vendor-spezifische Migrationen laden um Versionskollisionen (V3 doppelt) zu vermeiden.
    # Baseline V1 & V2 liegen identisch in db/migration und db/migration_postgresql nicht; deshalb fügen wir beide Pfade hinzu,
    # schließen aber die generische V3 aus, indem wir sie nach vendor Trennung künftig nicht mehr parallel pflegen.
    locations: classpath:db/migration_postgresql,classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    de.tubaf.planner: INFO
    org.hibernate.SQL: WARN
