server:
  port: 8084

spring:
  datasource:
    url: jdbc:h2:mem:tubaf-fresh;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        format_sql: true
        use_sql_comments: true
  
  flyway:
    enabled: false

tubaf:
  scraper:
    enabled: false

logging:
  level:
    de.tubaf.planner: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG